# https://vitepress.dev/reference/default-theme-config
nav:
  - text: ä¸»é¡µ
    link: /
  - text: å¿«é€Ÿå…¥é—¨
    link: /learn/
    activeMatch: /learn/
  - text: å‚è€ƒæ–‡æ¡£
    link: /guide/
    activeMatch: /guide/
  - text: WriteUp
    link: /wp/
    activeMatch: /wp/
    # items:
    #   - text: '2024'
    #     link: /wp/2024/
  - text: å½’æ¡£
    link: /archive/
    activeMatch: /archive/

sidebar:
  "/learn/":
    - text: å†™åœ¨å‰é¢
      link: /learn/
    - text: å¼€å§‹
      link: /learn/start

    - text: å„æ–¹å‘å…¥é—¨ä»‹ç»
      items:
        - text: Web ç½‘ç»œæ”»é˜²
          link: /learn/web
        - text: Crypto å¯†ç å­¦
          link: /learn/crypto
        - text: Reverse é€†å‘å·¥ç¨‹
          link: /learn/reverse
        - text: Pwn äºŒè¿›åˆ¶å®‰å…¨
          link: /learn/pwn
        - text: Misc æ‚é¡¹
          link: /learn/misc

    - text: å‚è€ƒæ•™ç¨‹
      items:
        - text: VSCode Python ç¯å¢ƒé…ç½®
          link: /learn/vscode-python
        - text: è·å– Linux å‘è¡Œç‰ˆ
          link: /learn/get-linux
        - text: WSL å®‰è£…æ•™ç¨‹
          link: /learn/install-wsl
        - text: åˆ‡æ¢è½¯ä»¶æº
          link: /learn/change-software-source
        - text: Pwn ç¯å¢ƒé…ç½®
          link: /learn/configure-pwn
        - text: Netcat ä½¿ç”¨æŒ‡å—
          link: /learn/nc

    - text: Q&A
      link: /learn/qa

    - text: è´¡çŒ®è€…
      link: /learn/credits

  "/guide/2025/":
    - text: èµ›äº‹ä¿¡æ¯
      link: /guide/2025/
    - text: å®£ä¼ 
      link: /guide/2025/promotion
    - text: è§£é¢˜å‚è€ƒ
      items:
        - text: Week 1
          link: /guide/2025/week1
        - text: Week 2
          link: /guide/2025/week2
        - text: Week 3
          link: /guide/2025/week3
        - text: Week 4
          link: /guide/2025/week4
        - text: Week 5
          link: /guide/2025/week5

  "/guide/2024/":
    - text: èµ›äº‹ä¿¡æ¯
      link: /guide/2024/
    - text: å®£ä¼ 
      link: /guide/2024/promotion
    - text: è§£é¢˜å‚è€ƒ
      items:
        - text: Week 1
          link: /guide/2024/week1
        - text: Week 2
          link: /guide/2024/week2
        - text: Week 3
          link: /guide/2024/week3
        - text: Week 4
          link: /guide/2024/week4
        - text: Week 5
          link: /guide/2024/week5
    - text: èŠ±çµ®æ–‡æ¡ˆ
      link: /guide/2024/copywriter

  "/guide/2023/":
    - text: èµ›äº‹ä¿¡æ¯
      link: /guide/2023/
    - text: å®£ä¼ 
      link: /guide/2023/promotion

  "/wp/2024/":
    - text: å‰è¨€
      link: /wp/2024/
    - text: Week 1
      items:
        - text: Pwn
          collapsed: true
          items:
            - text: Real Login
              link: /wp/2024/week1/pwn/real-login
            - text: Game
              link: /wp/2024/week1/pwn/game
            - text: Overwrite
              link: /wp/2024/week1/pwn/overwrite
            - text: Gdb
              link: /wp/2024/week1/pwn/gdb
        - text: Reverse
          collapsed: true
          items:
            - text: begin
              link: /wp/2024/week1/reverse/begin
            - text: base64
              link: /wp/2024/week1/reverse/base64
            - text: ezAndroidStudy
              link: /wp/2024/week1/reverse/ezandroidstudy
            - text: Simple_encryption
              link: /wp/2024/week1/reverse/simple-encryption
            - text: ez_debug
              link: /wp/2024/week1/reverse/ez-debug
        - text: Web
          collapsed: true
          items:
            - text: headach3
              link: /wp/2024/week1/web/headach3
            - text: ä¼šèµ¢å—ï¼Ÿ
              link: /wp/2024/week1/web/huiyingma
            - text: æ™ºæ¢°å±æœº
              link: /wp/2024/week1/web/zhixieweiji
            - text: PangBai è¿‡å®¶å®¶ï¼ˆ1ï¼‰
              link: /wp/2024/week1/web/pangbai1
            - text: è°¢è°¢çš®è›‹
              link: /wp/2024/week1/web/xiexiepidan
        - text: Crypto
          collapsed: true
          items:
            - text: xor
              link: /wp/2024/week1/crypto/xor
            - text: Base
              link: /wp/2024/week1/crypto/base
            - text: ä¸€çœ¼ç§’äº†
              link: /wp/2024/week1/crypto/yiyanmiaole
            - text: Strange King
              link: /wp/2024/week1/crypto/strange-king
        - text: Misc
          collapsed: true
          items:
            - text: decompress
              link: /wp/2024/week1/misc/decompress
            - text: WhereIsFlag
              link: /wp/2024/week1/misc/whereisflag
            - text: pleasingMusic
              link: /wp/2024/week1/misc/pleasingmusic
            - text: Labyrinth
              link: /wp/2024/week1/misc/labyrinth
            - text: å…‘æ¢ç 
              link: /wp/2024/week1/misc/duihuanma
    - text: Week 2
      items:
        - text: Pwn
          collapsed: true
          items:
            - text: EZ_fmt
              link: /wp/2024/week2/pwn/ez-fmt
            - text: Inverted World
              link: /wp/2024/week2/pwn/inverted-world
            - text: Bad Asm
              link: /wp/2024/week2/pwn/bad-asm
            - text: ez_game
              link: /wp/2024/week2/pwn/ez-game
            - text: My_GBC!!!!!
              link: /wp/2024/week2/pwn/my-gbc
        - text: Reverse
          collapsed: true
          items:
            - text: Pangbai æ³°æ‹‰è®°ï¼ˆ1ï¼‰
              link: /wp/2024/week2/reverse/pangbai-terra1
            - text: Ezencypt
              link: /wp/2024/week2/reverse/ezencypt
            - text: UPX
              link: /wp/2024/week2/reverse/upx
            - text: Ptrace
              link: /wp/2024/week2/reverse/ptrace
            - text: drink_tea
              link: /wp/2024/week2/reverse/drink_tea
            - text: Dirty_flowers
              link: /wp/2024/week2/reverse/dirty-flowers
        - text: Web
          collapsed: true
          items:
            - text: ä½ èƒ½åœ¨ä¸€ç§’å†…æ‰“å‡ºå…«å¥è‹±æ–‡å—
              link: /wp/2024/week2/web/bajuyingwen
            - text: é—å¤±çš„æ‹‰é“¾
              link: /wp/2024/week2/web/yishidelalian
            - text: å¤è¯»æœº
              link: /wp/2024/week2/web/fuduji
            - text: PangBai è¿‡å®¶å®¶ï¼ˆ2ï¼‰
              link: /wp/2024/week2/web/pangbai2
            - text: è°¢è°¢çš®è›‹ plus
              link: /wp/2024/week2/web/pidan-plus
        - text: Crypto
          collapsed: true
          items:
            - text: è¿™æ˜¯å‡ æ¬¡æ–¹ï¼Ÿç–‘æƒ‘ï¼
              link: /wp/2024/week2/crypto/jicifang
            - text: Since you konw something
              link: /wp/2024/week2/crypto/since-you-know-something
            - text: Just one and more than two
              link: /wp/2024/week2/crypto/just-one-and-more-than-two
            - text: èŒ¶é‡ŒèŒ¶æ°”
              link: /wp/2024/week2/crypto/chalichaqi
        - text: Misc
          collapsed: true
          items:
            - text: wireshark_checkin
              link: /wp/2024/week2/misc/wireshark-checkin
            - text: wireshark_secret
              link: /wp/2024/week2/misc/wireshark-secret
            - text: ä½ ä¹Ÿç©åŸç¥å—ï¼Ÿ
              link: /wp/2024/week2/misc/genshin
            - text: å­—é‡Œè¡Œé—´çš„ç§˜å¯†
              link: /wp/2024/week2/misc/zilihangjian
            - text: çƒ­å¿ƒåŠ©äººçš„å°æ˜åŒå­¦
              link: /wp/2024/week2/misc/xiaoming1
            - text: ç”¨æº¯æµä»ªè§è¯ä¼ç‰¹å°é£
              link: /wp/2024/week2/misc/futetaifeng
            - text: Herta's Study
              link: /wp/2024/week2/misc/herta
    - text: Week 3
      items:
        - text: Pwn
          collapsed: true
          items:
            - text: ä¸æ€è­°ãªscanf
              link: /wp/2024/week3/pwn/scanf
            - text: One Last B1te
              link: /wp/2024/week3/pwn/one-last-b1te
            - text: ezcanary
              link: /wp/2024/week3/pwn/ezcanary
            - text: Easy_Shellcode
              link: /wp/2024/week3/pwn/easy-shellcode
        - text: Reverse
          collapsed: true
          items:
            - text: 011vm
              link: /wp/2024/week3/reverse/011vm
            - text: simpleAndroid
              link: /wp/2024/week3/reverse/simpleandroid
            - text: SMc_math
              link: /wp/2024/week3/reverse/smc-math
            - text: flowering_shrubs
              link: /wp/2024/week3/reverse/flowering-shrubs
            - text: SecertsOfKawaii
              link: /wp/2024/week3/reverse/secrets-of-kawaii
            - text: PangBai è¿‡å®¶å®¶ï¼ˆ3ï¼‰
              link: /wp/2024/week3/reverse/pangbai3
            - text: å–å•¥åå¥½å‘¢
              link: /wp/2024/week3/reverse/qushaming
        - text: Web
          collapsed: true
          items:
            - text: è‡­çš®çš„è®¡ç®—å™¨
              link: /wp/2024/week3/web/jisuanqi
            - text: è‡­çš®è¸©è¸©èƒŒ
              link: /wp/2024/week3/web/caicaibei
            - text: è¿™ã€Œç…§ç‰‡ã€æ˜¯ä½ å—
              link: /wp/2024/week3/web/zhaopian
            - text: Include Me
              link: /wp/2024/week3/web/include-me
            - text: blindsql1
              link: /wp/2024/week3/web/blindsql1
        - text: Crypto
          collapsed: true
          items:
            - text: æ²¡ e è¿™èƒ½ç©ï¼Ÿ
              link: /wp/2024/week3/crypto/noenoplay
            - text: æ•…äº‹æ–°ç¼–
              link: /wp/2024/week3/crypto/gushixinbian
            - text: ä¸ç”¨è°¢å–µ
              link: /wp/2024/week3/crypto/buyongxiemiao
            - text: ä¸¤ä¸ªé»„é¹‚é¸£ç¿ æŸ³
              link: /wp/2024/week3/crypto/lianggehuangli
        - text: Misc
          collapsed: true
          items:
            - text: OSINT-MASTER
              link: /wp/2024/week3/misc/osint-master
            - text: BGM åäº†å—ï¼Ÿ
              link: /wp/2024/week3/misc/bgm-broken
            - text: AmazingGame
              link: /wp/2024/week3/misc/amazinggame
            - text: ez_jail
              link: /wp/2024/week3/misc/ez_jail
    - text: Week 4
      items:
        - text: Pwn
          collapsed: true
          items:
            - text: Reread
              link: /wp/2024/week4/pwn/reread
            - text: Maze_Rust
              link: /wp/2024/week4/pwn/maze_rust
            - text: MakeHero
              link: /wp/2024/week4/pwn/makehero
            - text: Sign in
              link: /wp/2024/week4/pwn/signin
        - text: Reverse
          collapsed: true
          items:
            - text: æ´ OVO
              link: /wp/2024/week4/reverse/dongovo
            - text: ezrust
              link: /wp/2024/week4/reverse/ezrust
            - text: easygui
              link: /wp/2024/week4/reverse/easygui
            - text: MazE
              link: /wp/2024/week4/reverse/maze
            - text: PlzDebugMe
              link: /wp/2024/week4/reverse/plzdebugme
        - text: Web
          collapsed: true
          items:
            - text: blindsql2
              link: /wp/2024/week4/web/blindsql2
            - text: ezpollute
              link: /wp/2024/week4/web/ezpollute
            - text: ezcmsss
              link: /wp/2024/week4/web/ezcmsss
            - text: chocolate
              link: /wp/2024/week4/web/chocolate
            - text: éšè—çš„å¯†ç 
              link: /wp/2024/week4/web/hidden-password
            - text: PangBai è¿‡å®¶å®¶ï¼ˆ4ï¼‰
              link: /wp/2024/week4/web/pangbai4
        - text: Crypto
          collapsed: true
          items:
            - text: åœ£çŸ³åŒ•é¦–
              link: /wp/2024/week4/crypto/shengshibishou
            - text: æ¬§æ‹‰æ¬§æ‹‰ï¼ï¼
              link: /wp/2024/week4/crypto/euler
            - text: ä¿±ä»¥æˆ‘ä¹‹å
              link: /wp/2024/week4/crypto/wiener
        - text: Misc
          collapsed: true
          items:
            - text: æ“…é•¿éŸ³æ¸¸çš„å°æ˜åŒå­¦
              link: /wp/2024/week4/misc/xiaoming2
            - text: æ“…é•¿åŠ å¯†çš„å°æ˜åŒå­¦
              link: /wp/2024/week4/misc/xiaoming3
            - text: ezblockchain
              link: /wp/2024/week4/misc/ezblockchain
            - text: æ‰«ç é¢†å– flag
              link: /wp/2024/week4/misc/saoma
            - text: Alt
              link: /wp/2024/week4/misc/alt
    - text: Week 5
      items:
        - text: Pwn
          collapsed: true
          items:
            - text: C_or_CPP
              link: /wp/2024/week5/pwn/c_or_cpp
            - text: Simple_Shellcode
              link: /wp/2024/week5/pwn/simple_shellcode
            - text: No Output
              link: /wp/2024/week5/pwn/no_output
            - text: EldenRing
              link: /wp/2024/week5/pwn/eldenring
        - text: Reverse
          collapsed: true
          items:
            - text: MY_ARM
              link: /wp/2024/week5/reverse/my_arm
            - text: Lock
              link: /wp/2024/week5/reverse/lock
            - text: jun...junkcode?
              link: /wp/2024/week5/reverse/junkcode
            - text: PangBai æ³°æ‹‰è®°ï¼ˆ2ï¼‰
              link: /wp/2024/week5/reverse/pangbai-terra2
            - text: PangBai æ³°æ‹‰è®°ï¼ˆ3ï¼‰
              link: /wp/2024/week5/reverse/pangbai-terra3
            - text: Ohn_flutter!!!
              link: /wp/2024/week5/reverse/ohn_flutter
        - text: Web
          collapsed: true
          items:
            - text: PangBai è¿‡å®¶å®¶ï¼ˆ5ï¼‰
              link: /wp/2024/week5/web/pangbai5
            - text: è‡­çš®å¹æ³¡æ³¡
              link: /wp/2024/week5/web/choupichuipaopao
            - text: è‡­çš®çš„ç½‘ç«™
              link: /wp/2024/week5/web/choupidewangzhan
            - text: ez_redis
              link: /wp/2024/week5/web/ez_redis
            - text: sqlshell
              link: /wp/2024/week5/web/sqlshell
        - text: Crypto
          collapsed: true
          items:
            - text: RSA? cmd5!
              link: /wp/2024/week5/crypto/rsa_cmd5
            - text: easy_ecc
              link: /wp/2024/week5/crypto/easy_ecc
            - text: æ²¡ e ä¹Ÿèƒ½ç©
              link: /wp/2024/week5/crypto/noe
            - text: å­¦ä»¥è‡´ç”¨
              link: /wp/2024/week5/crypto/xueyizhiyong
            - text: æ ¼æ ¼ä½ å¥½æ£’
              link: /wp/2024/week5/crypto/gegenihaobang
        - text: Misc
          collapsed: true
          items:
            - text: PlzLoveMe
              link: /wp/2024/week5/misc/plzloveme
            - text: zipmaster
              link: /wp/2024/week5/misc/zipmaster
            - text: pyjail
              link: /wp/2024/week5/misc/pyjail
            - text: I wanna be a Rust Master
              link: /wp/2024/week5/misc/rust-master

  "/wp/2025/":
    - text: å‰è¨€
      link: /wp/2025/
    - text: Week 1
      items:
        - text: Pwn
          collapsed: true
          items:
            - text: overflow
              link: /wp/2025/week1/pwn/overflow
            - text: "GNU Debugger"
              link: /wp/2025/week1/pwn/gdb_debugger
        - text: Web
          collapsed: true
          items:
            - text: multi-headach3
              link: /wp/2025/week1/web/multi-headach3
            - text: strange_login
              link: /wp/2025/week1/web/strange_login
            - text: é»‘å®¢å° W çš„æ•…äº‹ï¼ˆ1ï¼‰
              link: /wp/2025/week1/web/hacker-w-story-1
            - text: å®‡å®™çš„ä¸­å¿ƒæ˜¯ PHP
              link: /wp/2025/week1/web/yu-zhou-de-zhong-xin-shi-php
            - text: åˆ«ç¬‘ï¼Œä½ ä¹Ÿè¿‡ä¸äº†ç¬¬äºŒå…³
              link: /wp/2025/week1/web/bie-xiao-ni-ye-guo-bu-liao-di-er-guan
            - text: æˆ‘çœŸå¾—æ§åˆ¶ä½ äº†
              link: /wp/2025/week1/web/wo-zhen-dei-kong-zhi-ni-le
        - text: Crypto
          collapsed: true
          items:
            - text: å°è·³è›™
              link: /wp/2025/week1/crypto/xiaotiaowa
            - text: å”¯ä¸€è¡¨ç¤º
              link: /wp/2025/week1/crypto/weiyibiaoshi
            - text: éšæœºæ•°ä¹‹æ—… 1
              link: /wp/2025/week1/crypto/suijishu1
            - text: sagemath
              link: /wp/2025/week1/crypto/sagemath
        - text: Misc
          collapsed: true
          items:
            - text: å‰æœ‰æ–‡å­—ï¼Œæ‰€ä»¥æœç´¢å¾ˆæœ‰ç”¨
              link: /wp/2025/week1/misc/sousuo
            - text: æˆ‘ä¸è¦é©å‘½å¤±è´¥
              link: /wp/2025/week1/misc/geming
            - text: EZ_fence
              link: /wp/2025/week1/misc/ez_fence
    - text: Week 2
      items:
        - text: Web
          collapsed: true
          items:
            - text: DD åŠ é€Ÿå™¨
              link: /wp/2025/week2/web/dd-jia-su-qi
            - text: å°Eçš„ç®¡ç†ç³»ç»Ÿ
              link: /wp/2025/week2/web/es-manage-system
            - text: æç‚¹å“¦æ¶¦å‰åƒåƒ ğŸŠ
              link: /wp/2025/week2/web/get-oranges-to-eat
    - text: Week 3
      items:
        - text: Web
          collapsed: true
          items:
            - text: å°Eçš„ç§˜å¯†è®¡åˆ’
              link: /wp/2025/week3/web/es-secret-plan
            - text: ez_chain
              link: /wp/2025/week3/web/ez_chain
            - text: mirror_gate
              link: /wp/2025/week3/web/mirror_gate
